### ISSUE TITLE
Can't Connect to Core Lightning: ECONNREFUSED 127.0.0.1:3092

### ISSUE THREAD

**Issue by TheFockinFury** [Ride-The-Lightning/RTL#1218]
I'm attempting to install RTL via Docker and am currently unable to connect to Lightning (CLN). My node is built following the Raspibolt guide for CLN.

I came across this issue but the resolution here did not work for me: https://github.com/Ride-The-Lightning/RTL/issues/1041

Confirming that c-lightning-REST is running on my machine as per the logs:
```
$ tail -f /data/lightningd/cln.log 
2023-04-17T14:37:17.764Z UNUSUAL plugin-clrest.js: --- Starting the cl-rest server ---
2023-04-17T14:37:17.770Z INFO    lightningd: --------------------------------------------------
2023-04-17T14:37:17.770Z INFO    lightningd: Server started with public key 038986fa4b74a901d69c0a7c5428d51f73498c4beb43296af97a973295d050de89, alias NSA Surveillance Van (color #cc00ff) and lightningd v23.02.2
2023-04-17T14:37:17.771Z UNUSUAL plugin-clrest.js: --- cl-rest api server is ready and listening on :::3092 ---
2023-04-17T14:37:17.771Z UNUSUAL plugin-clrest.js: --- cl-rest doc server is ready and listening on :::4091 ---
```

My c-lightning-REST config is as follows:
```
{
    "PORT": 3092,
    "DOCPORT": 4091,
    "PROTOCOL": "http",
    "EXECMODE": "production",
    "RPCCOMMANDS": ["*"],
    "DOMAIN": "localhost",
    "LNRPCPATH": "/home/lightningd/.lightning/bitcoin"
}
```

My RTL config is:
```
{
  "port": "3000",
  "defaultNodeIndex": 1,
  "dbDirectoryPath": "/root/database/node-1",
  "SSO": {
    "rtlSSO": 0,
    "rtlCookiePath": "",
    "logoutRedirectLink": ""
  },
  "nodes": [
    {
      "index": 1,
      "lnNode": "CLN Node",
      "lnImplementation": "CLN",
      "Authentication": {
        "macaroonPath": "/home/rtl",
        "configPath": "/data/lightningd/config"
      },
      "Settings": {
        "userPersona": "OPERATOR",
        "themeMode": "NIGHT",
        "themeColor": "INDIGO",
        "logLevel": "ERROR",
        "lnServerUrl": "http://127.0.0.1:3092",
        "fiatConversion": true,
        "currencyUnit": "USD",
        "enableOffers": true
      }
    }
  ],
  "defaultNodeIndex": 1,
  "multiPassHashed": "[redacted]",
  "secret2fa": "[redacted]"
}
```

And finally, my docker-compose:
```
version: '3.3'
services:
    rtl:
        container_name: rtl
        environment:
            - RTL_CONFIG_PATH=/RTLConfig
        volumes:
            - 'config:/RTLConfig'
            - '/home/rtl:/home/rtl:ro'
            - 'db:/RTL/database'
        user: '1007:1007'
        ports:
            - '3000:3000/tcp'
        image: 'shahanafarooqui/rtl:0.13.6'
volumes:
    config:
    db:
```

In docker-compose above, user 1007 is my user for RTL and I've chowned the access.macaroon file to be owned by that user. 

Any advice on where to turn next for troubleshooting would be much appreciated!

**Your environment**
- Version of RTL v0.13.6
- Version of c-lightning v23.02.2
- Version of c-lightning-REST v0.10.2
- Version of bitcoind v24.0.1
- Operating system Ubuntu 22.04.2 / Raspibolt
