### ISSUE TITLE
RTL_PASS doesn't work in Docker and where is the password stored on disk ?

### ISSUE THREAD

**Issue by iangregsondev** [Ride-The-Lightning/RTL#267]
Hi,

I wonder if anyone can help ?

Using the latest docker image

```
    image: shahanafarooqui/rtl:0.6.7
```

and have the env variable set

```
      RTL_PASS: ${RTL_PASS}
```

But the password never takes, actually doing a search for process.env - i couldn't even find the use of that env variable.

No problem, I set it manually but when I rebuild the container the password resets. This is, of course, is due to not having any volumes.

So I want to create a volume, where are the passwords stored on disk so I can set up the correct volume in my docker-compose.yml file.

There are the environment variables I am using, that was taken from an example in the repository.

```
    environment:
      PORT: ${RTL_PORT}
      MACAROON_PATH: /lnd/chain/bitcoin/testnet
      LN_SERVER_URL: https://${LIGHTNING_HOST}:${LIGHTNING_REST_PORT}/v1
      CONFIG_PATH: ""
      RTL_PASS: ${RTL_PASS}
```

Any ideas?

Thanks
