### ISSUE TITLE
How to set password to docker image shahanafarooqui/rtl:0.8.3 ?

### ISSUE THREAD

**Issue by limpbrains** [Ride-The-Lightning/RTL#400]
**Describe the bug**
I'm trying to pass `RTL_PASS` or `MULTI_PASS` to environment variables in my docker-compose. But password is still default.

**To Reproduce**
I'm running RTL with following docker-compose.yml:

```
  bitcoin_rtl:
    image: shahanafarooqui/rtl:0.8.3
    restart: unless-stopped
    environment:
      LND_SERVER_URL: http://lnd_bitcoin:8080/v1
      MACAROON_PATH: /etc/lnd
      RTL_CONFIG_PATH: /data/
      LND_CONFIG_PATH: /etc/lnd/lnd.conf
      BITCOIND_CONFIG_PATH: /etc/bitcoin/bitcoin.conf
      HOST: "bitcoin_rtl"
      RTL_PASS: "xxxxxx"
      MULTI_PASS: "xxxxxx"
```

When I'm trying to login to RTL with "xxxxxx" it says password is wrong. Default "password" works fine.

**Environment**
* Version of `RTL` - 0.8.3
* Version of `lnd` - v0.10.2-beta
* Version of `bitcoind` - 0.19.0.1
* Operating system - ubuntu 20.04

**Additional context**

PS.
docker example is obsolete, it would be nice to have a fresh one.

Thank you for awesome project!
