### ISSUE TITLE
Problem with Docker and RTL-Config.json 

### ISSUE THREAD

**Issue by MarcSky** [Ride-The-Lightning/RTL#416]
**Describe the bug**
Hello. I try to connect to my LND node from RTL.
I using docker for executing RTL service and when I try to open LND Config from RTL web I have next error message in logs
```
INFO: RTLConf => Getting Node Config
INFO: RTLConf => Selected Node Updated To: "Node 1"
ERROR: Authenticate(36) => Invalid Password! (Here not working my password from RTL-Config.json)
INFO: RTLConf => Node Type: ln, File Path: /root/.lnd/lnd.conf
ERROR: Conf(171) => Reading Conf Failed!
```
Its looks like docker can't find RTL-Config.json (because also not working my password) or he can't find lnd.conf

```
{
  "multiPass": "helloworld",
  "port": "3000",
  "defaultNodeIndex": 1,
  "SSO": {
    "rtlSSO": 0,
  },
  "nodes": [
    {
      "index": 1,
      "lnNode": "LND TEST",
      "Authentication": {
        "macaroonPath": "/lnd",
        "configPath": "/lnd/lnd.conf"
      },
      "Settings": {
        "userPersona": "OPERATOR",
        "themeMode": "DAY",
        "themeColor": "PURPLE",
        "channelBackupPath": "/backup",
        "enableLogging": true,
        "fiatConversion": false,
        "lnServerUrl": "https://localhost:10550/v1",
      }
    }
  ]
}
```

```
version: '3.6'

volumes:
  lnd:
  RTL:
  backup:

services:
  rtl-service:
    image: shahanafarooqui/rtl:0.8.4
    restart: unless-stopped
    ports:
      - 3000:3000
    environment:
      PORT: 3000
      HOST: 0.0.0.0
      MACAROON_PATH: /lnd
      LN_SERVER_URL: https://localhost:10550/v1
      RTL_CONFIG_PATH: /RTL
    volumes:
      - lnd:/lnd
      - RTL:/RTL
      - backup:/backup
```

Folders lnd RTL and backup lie in same folder with docker-compose.yml, I don't think that I put wrong path in docker-compose.

**To Reproduce**
1. Go to RTL web and open tab LND conf

**Your environment**
* Version of `RTL` **0.8.4**
* Version of `lnd` **v0.10.0-beta**
* Version of `btcd`, `bitcoind`, **0.19.0**
* Browser & browser version **Chrome**
* Operating system (`uname -a` on *Nix) **MacOS**
