### ISSUE TITLE
Can't open RTL when run from docker 

### ISSUE THREAD

**Issue by brmdbr** [Ride-The-Lightning/RTL#514]
**Describe the bug**
I'm trying to run rtl from a docker container but I run in the following issue, there is nothing when I go to the url (http://localhost:3001) presented at the logs. 

Logs:
```
Start...config creation at: /RTL/RTL-Config.json
End...config creation.
Server is up and running, please open the UI at http://localhost:3001
```

Part of my docker-compose file:
```
rtl:
    image: shahanafarooqui/rtl:0.9.1
    container_name: rtl
    environment:
      LN_IMPLEMENTATION: ECL
      LN_SERVER_URL: http://eclair:${LIGHTNING_PORT}
      LN_API_PASSWORD: ${LIGHTNING_PASS}
      BITCOIND_CONFIG_PATH: /etc/bitcoin/bitcoin.conf
      RTL_SSO: 1
      RTL_COOKIE_PATH: /data/.cookie
      PORT: 3001
      LOGOUT_REDIRECT_LINK: /server/services
    volumes:
      - "bitcoin_datadir:/etc/bitcoin"
      - "eclair_datadir:/etc/eclair"
      - "rtl_datadir:/data"
    expose:
      - "3001"
    depends_on:
      - eclair
    restart: unless-stopped
```

Am I missing something here or?
