### ISSUE TITLE
0.12.1 fails to restart after docker image update

### ISSUE THREAD

**Issue by NicolasDorier** [Ride-The-Lightning/RTL#951]
So [we updated RTL](https://github.com/btcpayserver/btcpayserver-docker/commit/8582e453c30a63fb30e10622aa31f05c29a8d039) to the latest version on BTCPayServer.

It worked on my server, however, for another user, his RTL is stuck and can't restart anymore.

```

Error: Error:
RTL Password cannot be set with SSO. Please set SSO as 0 or remove password.
    at ConfigService.setServerConfiguration (file:///RTL/backend/utils/config.js:333:23)
    at ExpressApplication.loadConfiguration (file:///RTL/backend/utils/app.js:32:25)
    at new ExpressApplication (file:///RTL/backend/utils/app.js:80:14)
    at file:///RTL/rtl.js:10:13
    at ModuleJob.run (node:internal/modules/esm/module_job:185:25)
    at async Promise.all (index 0)
    at async ESMLoader.import (node:internal/modules/esm/loader:281:24)
    at async loadESM (node:internal/process/esm_loader:88:5)
    at async handleMainPromise (node:internal/modules/run_main:65:12)
[2/10/2022, 4:54:35 AM] ERROR: Config => Something went wrong while configuring the node server:
Error:
RTL Password cannot be set with SSO. Please set SSO as 0 or remove password..

file:///RTL/backend/utils/config.js:333
                throw new Error(err);
                      ^

Error: Error:
RTL Password cannot be set with SSO. Please set SSO as 0 or remove password.
    at ConfigService.setServerConfiguration (file:///RTL/backend/utils/config.js:333:23)
    at ExpressApplication.loadConfiguration (file:///RTL/backend/utils/app.js:32:25)
    at new ExpressApplication (file:///RTL/backend/utils/app.js:80:14)
    at file:///RTL/rtl.js:10:13
    at ModuleJob.run (node:internal/modules/esm/module_job:185:25)
    at async Promise.all (index 0)
    at async ESMLoader.import (node:internal/modules/esm/loader:281:24)
    at async loadESM (node:internal/process/esm_loader:88:5)
    at async handleMainPromise (node:internal/modules/run_main:65:12)
```

Here is our docker-compose that we never touched.

```
  bitcoin_rtl:
    image: shahanafarooqui/rtl:0.12.1
    restart: unless-stopped
    environment:
      LND_SERVER_URL: http://lnd_bitcoin:8080/v1
      MACAROON_PATH: /etc/lnd
      SWAP_SERVER_URL: https://lnd_bitcoin:8081/v1
      SWAP_MACAROON_PATH: /etc/lndloop
      RTL_CONFIG_PATH: /data/
      LND_CONFIG_PATH: /etc/lnd/lnd.conf
      BITCOIND_CONFIG_PATH: /etc/bitcoin/bitcoin.conf
      RTL_SSO: 1
      RTL_COOKIE_PATH: /data/.cookie
      LOGOUT_REDIRECT_LINK: /server/services
    volumes:
      - "bitcoin_datadir:/etc/bitcoin"
      - "lnd_bitcoin_datadir:/etc/lnd"
      - "lndloop_bitcoin_datadir:/etc/lndloop"
      - "lnd_bitcoin_rtl_datadir:/data"
    expose:
      - "3000"
    links:
      - lnd_bitcoin
```
